name: Deploy Backend to Hugging Face Space

on:
  push:
    branches: [ "main" ]
    paths: [ "backend/**" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true

    - name: Sync to Hugging Face Hub
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git config --global http.https://huggingface.co/.extraheader "Authorization: Bearer $HF_TOKEN"

        git clone https://huggingface.co/spaces/$HF_SPACE_REPO temp

        rm -rf temp/*

        cp -r backend/* temp/

        cd temp
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Sync backend from GitHub repo on $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
        git push origin main